### ISSUE TITLE
array bound mismatch

### ISSUE THREAD

**Issue by w-vdh** [modern-fortran/stock-prices#2]
In the function crossneg, should this line
`    res = pack(res, smaller(2:) .and. greater(:size(x-1)))`
not read 
`    res = pack(res, smaller(2:) .and. greater(:size(x)-1))`?

And likewise for the corresponding line in the function crosspos.

**Comment by milancurcic** [comment]
Yes, it should! Good catch. Would you like to submit a PR with the fix?
