### ISSUE TITLE
stock-prices/data/get_data.sh

### ISSUE THREAD

**Issue by GGabc** [modern-fortran/stock-prices#7]
Please add comments to this file as to what "language" it is run as.  I finally figured it out as Unix shell, but nothing wrong in helping others avoid the time wasted figuring it out.  BTW:  I don't have a Linux shell installed.  Tried a couple of times to install Linux, but honestly, the people setting up Linux really don't want people to be able to successfully install a functioning system.

**Comment by milancurcic** [comment]
Thanks! I just made an edit.

What OS are you running?

If Windows, have you tried the Windows Subsystem for Linux?

**Comment by GGabc** [comment]
I am running Windows 10 Pro.  I have VMware installed with an Ubuntu Linux.  Installing that OS was a chore.  Still buggy and incomplete.

Thanks for the suggestion of Windows Subsystem for Linux.  However, this page of info says that an existing Linux has to be installed in order to install the Linux OS into WSL.  For my minimal use, that is only compounding the issues.
https://learn.microsoft.com/en-us/windows/wsl/use-custom-distro

Maybe the MS Store  distributions can be installed without an existing Linux?  I got this note from trying WSL at a commandline.
"Distributions can be installed by visiting the Microsoft Store: https://aka.ms/wslstore "

Your Market Analysis example uses at least 3 languages that I have found.  Although I know python and Unix generally well enough to read them, most people don't have that level of experience.  A comment at the top would help.  On the specific Unix script, I was not sure without research that it was a Unix script.  In short snippets, there is too much similarity between languages to quickly determine what language it is, or just is it a particular coder's formatting of another language.



________________________________

**Comment by milancurcic** [comment]
Yes, the guide you linked is for installing custom distros that are not in the Windows store. Last summer I followed this guide to install Ubuntu on Windows 11 and the process was relatively smooth:

https://learn.microsoft.com/en-us/windows/wsl/install

> Your Market Analysis example uses at least 3 languages that I have found.  Although I know python and Unix generally well enough to read them, most people don't have that level of experience.  A comment at the top would help.  On the specific Unix script, I was not sure without research that it was a Unix script.  In short snippets, there is too much similarity between languages to quickly determine what language it is, or just is it a particular coder's formatting of another language.

I agree with you, and this situation is not ideal. For some examples, to get to something concrete and visible like a chart, I needed to resort to tools other than Fortran. Indeed, it's unfortunate that this is not inclusive toward Windows users. I did the best I could considering the limited scope of the book (hands-on examples for beginning Fortran programmers), and regarding my limited experience with macOS and Windows.
